### ISSUE TITLE
Missing *But* in Gherkin words

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/pygmentslexer#11]
There is a missing Gherkin word in `robotframeworklexer`, it misses *But*. This is the one we have in RIDE's modified code:
```python
class GherkinTokenizer(object):
    _gherkin_prefix = re.compile('^(Given|When|Then|And|But) ', re.IGNORECASE)
```

**Comment by pekkaklarck** [comment]
Good catch. I'll add this to v1.1.1 and release that after RoboCon. Will then create PR with all these fixes to Pygments.
